const items = [
    {
        id: 0,
        name: "Sakarias Armchair",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 392,
        rating: 0,
        img: "chair-01.png",
        category: "chair",
    },
    {
        id: 1,
        name: "Baltsar Chair",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 299,
        rating: 4,
        img: "chair-02.png",
        category: "chair",
    },
    {
        id: 2,
        name: "Anjay Chair",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 519,
        rating: 5,
        img: "chair-03.png",
        category: "chair",
    },
    {
        id: 3,
        name: "Nyantuy Chair",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 299,
        rating: 3,
        img: "chair-04.png",
        category: "chair",
    },
    {
        id: 4,
        name: "Emma",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 611,
        rating: 5,
        img: "bed-emma_eur611.png",
        category: "bed",
    },
    {
        id: 5,
        name: "Nikol",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 213,
        rating: 3,
        img: "bed-nikol_eur213t.png",
        category: "bed",
    },
    {
        id: 6,
        name: "Vicento",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 213,
        rating: 4,
        img: "bed-vicento.png",
        category: "bed",
    },
    {
        id: 7,
        name: "Atlanta home cinema",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 761,
        rating: 5,
        img: "sofa-Atlanta.png",
        category: "sofa",
    },
    {
        id: 8,
        name: "Walter",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 3295,
        rating: 5,
        img: "sofa-walter.png",
        category: "sofa",
    },
    {
        id: 9,
        name: "Oasis",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 3325,
        rating: 5,
        img: "sofa_oasis.png",
        category: "sofa",
    },
    {
        id: 10,
        name: "Armstrong Trumpet",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 594,
        rating: 5,
        img: "lamp-armstrong_trumpet.png",
        category: "lamp",
    },
    {
        id: 11,
        name: "Stag Head",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 379,
        rating: 4,
        img: "lamp-stag-head.png",
        category: "lamp",
    },
    {
        id: 12,
        name: "Acanthus",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 296,
        rating: 4,
        img: "lamp-acanthus.png",
        category: "lamp",
    },
    {
        id: 13,
        name: "Angel",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        leftItems: 10,
        price: 450,
        rating: 5,
        img: "lamp-angel.png",
        category: "lamp",
    },
];